name: "Trigger CircleCI Pipeline"
description: "Trigger pipelines on CircleCI for any event on GitHub."
branding:
  icon: "check-circle"
  color: "green"
inputs:
  parameters:
    required: false
    description: |
      An optional additional parameters.
      Will be available on the CircleCI pipeline.
      Format as JSON string, eg: '{"deploy": "prod"}'
runs:
  using: "node12"
  main: "dist/index.js"
